apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-devops-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gcp
  template:
    metadata:
      labels:
        app: gcp
    spec:
      containers:
        - name: gcp-devops-container
          image: gcr.io/george-test-335313/gcpdevop:latest
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              value: "5000"
